import type { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app'
}

export default function Home() {
  return (
    <div>
    </div>
  )
}
