import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Preview",
  description: "Generated by create next app",
};

export default function Home () {
  return (
    <div>
      <div>
      <p className="text-4xl">hola saludos</p></div> 
    </div>
  )
}
