import type { Metadata } from "next";
import './jaja.style.css'
import { Prueba } from "../components/prueba/prueba";


export const metadata: Metadata = {
  title: "Preview",
  description: "Generated by create next app",
};

export default function Home () {
  return (
    <div>
      <Prueba/>
    </div>
  )
}
