import type { Metadata } from "next";
import { Prueba } from "../components/prueba/prueba.component";

export const metadata: Metadata = {
  title: "Preview",
  description: "Generated by create next app",
};

export default function Home () {
  return (
    <div>
      <Prueba/>
    </div>
  )
}
